name: anythingllm-last

networks:
  anything-llm-last:
    driver: bridge

services:
  anything-llm-last:
    container_name: anythingllm-last
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - "../server/storage:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - anything-llm-last
    extra_hosts:
      - "host.docker.internal:host-gateway"
